line-length = 120
target-version = "py312"
fix = true

[lint]
select = ["E","F","B","I","UP"]
ignore = ["E203","B008"]

[lint.isort]
known-first-party = ["awa_common","services"]
combine-as-imports = true
